### ISSUE TITLE
Any objection to me tweaking this to support AWS, Azure and Vagrant boxes?

### ISSUE THREAD

**Issue by JonTheNiceGuy** [wimpysworld/desktopify#14]
I'm already doing a little bit of this with my Ansible scripts, but this seems far more thorough (surprisingly ;) ). It'd be interesting to make this more akin to an OEM'ing tool, with architecture consideration for RPi.

Does that make sense? I'm not sure if you've covered this in the video, as I only caught a couple of minutes of it...

**Comment by flexiondotorg** [comment]
If you feel this needs discussion, then please join our Discord where we can have a chat :slightly_smiling_face:  Or, submit a pull request and we can review the feature there :+1: 

  * https://discord.gg/hy7uZfX
