### ISSUE TITLE
git clone asks for password

### ISSUE THREAD

**Issue by siduxdevil** [wimpysworld/desktopify#22]
I can git clone desktopify to my workstation without a problem. When I try to git clone from Ubuntu server on a RasPi, I get asked for a password!? All I can give it are my github credentials but then I get: fatal: repository … not found. Can someone please explain?

**Comment by lah7** [comment]
You can clone using SSH or HTTPS. Likely you'll want to use HTTPS as this doesn't require you to login:

    git clone https://github.com/wimpysworld/desktopify.git

**Comment by superpowter77** [comment]
I tried as instructed above with HTTPS as follows:
git clone https://github.com/wimpysworld/desktopify.git
and still asking for a username and password. Cannot get pass it.
I'm re-flashing to see what happens. This is suppose to be straightforward...

**Comment by evanmiller29** [comment]
I got that, but then I restarted my pi and git cloned and it worked @jtremblant

**Comment by superpowter77** [comment]
It finally worked for me after reflashing again using etcher this time. Thank's

**Comment by basem95148** [comment]
Don't use sudo  just use     git clone https://github.com/wimpysworld/desktopify.git
worked for me that way.

**Comment by orochikun** [comment]
Same problem , reflashed restarted , same issue 
Also I attempted clone with another github proyect and that worked with no hickups
Any ideas ?

**Comment by orochikun** [comment]
Nevermind the url was incorrect TRUST on this make suuuper sure you are typing the correct url
