### ISSUE TITLE
Windows resolutions 2560x1080

### ISSUE THREAD

**Issue by ranrinc** [wimpysworld/desktopify#23]
Testing on ubuntu-mate and fail to adjust resolutions. Is there away to do it?

It work on raspiOS without have to do anything btw.

Solve by actually setting your config.txt. Anyway for you guys who would like to run ubuntu-mate bootable from SSD Drive only then you should try [my guide](https://krdesigns.com/articles/Boot-raspbian-ubuntu-20.04-official-from-SSD-without-microsd) and also it will adjust to 2560x1080 screen automatically.. AWESOME

**Comment by kylagit** [comment]
Try this: https://www.dedoimedo.com/computers/rpi4-ubuntu-mate-hw-video-acceleration.html

**Comment by htr200** [comment]
Wow,can you teach me?I am new for Github,I m Chinese.

**Comment by kylagit** [comment]
> Wow,can you teach me?I am new for Github,I m Chinese.

Its not my document
