### ISSUE TITLE
Start menu disappeared

### ISSUE THREAD

**Issue by dikodahan** [wimpysworld/desktopify#26]
Hey,

My start menu disappeared for some reason. was wondering if you can share any sort of reset/re-enable command to fix this?

**Comment by kylagit** [comment]
Which desktop?

**Comment by dikodahan** [comment]
The one installed by your installer.

**Comment by dikodahan** [comment]
Ran the new setup with the a fresh install of Ubuntu Mate. Everything good so far.
Closing the issue.
