### ISSUE TITLE
Argon one case

### ISSUE THREAD

**Issue by Fbabsail** [wimpysworld/desktopify#37]
When I try to install the argon one case configuration file I get this: Unable to locate package raspi-gpio

I guess it has to do with the different way gpio works on desktopify, so if anyone know a way to edit the script i would be very thankful.

This is the script: https://download.argon40.com/argon1.sh

**Comment by grammus** [comment]
Someone has done one here: https://github.com/meuter/argon-one-case-ubuntu-20.04

(Edit: and I'm using it, and it's working)

**Comment by flexiondotorg** [comment]
Fixed via this project - https://github.com/wimpysworld/argon1-ubuntu
