### ISSUE TITLE
Can you run desktopify multiple times on same raspberry pi?

### ISSUE THREAD

**Issue by EarthModule** [wimpysworld/desktopify#38]
There is no mention of this in the Readme, but I would like to install multiple Desktop Envs for my pi using Desktopify. Is this possible in the current implementation?

**Comment by kylagit** [comment]
No, the desktops may conflict with eachover

**Comment by EarthModule** [comment]
Ok, thank you for the clarification! I really love Desktopify, keep up the good work!
