### ISSUE TITLE
[Suggestion] Add Regolith Linux as Desktop Option

### ISSUE THREAD

**Issue by dragon99919** [wimpysworld/desktopify#45]
Since Regiloth can be installed over ubuntu with a single package (see [here](https://regolith-linux.org/download/)) I think it would make a great addition to the project, since the tiling window desktops is what would be rather welcome to use. I already do, but I've just installed a package to the server directly. Thou not many people might know about it, since it's not official.

**Comment by bigpod98** [comment]
problem is it needs adding a ppa

**Comment by flexiondotorg** [comment]
Sorry, I don't plan to add support for non-official Ubuntu flavours.
