### ISSUE TITLE
[Error] "Is a directory"

### ISSUE THREAD

**Issue by dx-0** [wimpysworld/desktopify#46]
When following the instructions, I get the message "is a directory" after entering `sudo ./desktopify --de lubuntu`

**Comment by savioruz** [comment]
`sudo ./home/ubuntu/desktopify/desktopify --de lubuntu`
or try with `cd desktopify` first then do `sudo ./desktopify --de lubuntu`

**Comment by dx-0** [comment]
Thanks!

**Comment by bigpod98** [comment]
to explain what the issue is when you git clone contents of a git repository are dumped into a folder with the name of git repository so in this case desktopify do you as jakues explained first need to go into the desktopify directory to then run the command to launch desktopify

**Comment by dx-0** [comment]
Thanks for the explanation.
