### ISSUE TITLE
Add Ubuntu 20.10 support

### ISSUE THREAD

**Issue by kylagit** [wimpysworld/desktopify#65]
Please add Ubuntu 20.10 support to dekstopify, something like this

# Check if we're running 20.04 or 20.10
CODENAME=$(lsb_release -cs)
if [ "${CODENAME}" != "focal, groovy" ]; then
  echo "[!] This script is only intended to run on Ubuntu 20.04 or 20.10."
  exit 1
fi

I dont know if 

if [ "${CODENAME}" != "focal, groovy" ]; then

Is correct but you should understand what i mean

**Comment by hanseatv6** [comment]
Here is a working example:

if [ "${CODENAME}" != "focal" || "groovy" ]; then

**Comment by hcet14** [comment]
Should be closed. Pi Imager handles it.

**Comment by flexiondotorg** [comment]
Duplicate of #59
