### ISSUE TITLE
Line 237 fails ShellCheck

### ISSUE THREAD

**Issue by teward** [wimpysworld/desktopify#68]
https://github.com/wimpysworld/desktopify/blob/50b72f96ea921618cf30b85b6ba147fc929a85cb/desktopify#L237

Per ShellCheck, this is an invalid implementation - instead you should be using a `grep -q` instead of an `[-n ... ]` comparison check.

This breaks all CI tests.

**Comment by flexiondotorg** [comment]
Fixed via #69
