### ISSUE TITLE
How is this different than running `sudo apt install [desktop-name]-desktop`?

### ISSUE THREAD

**Issue by thammarith** [wimpysworld/desktopify#70]
Hi, I'm quite new to the Ubuntu world. I read the [Ubuntu's guide to install a desktop over the server image](https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#5-install-a-desktop). The commands for installing are very few comparing to desktopify's.

So I wonder what else does it do and why should I use desktopify over running just `sudo apt install [desktop-name]-desktop`?

Thanks!

**Comment by moeenio** [comment]
desktopify writes some config to `/boot/config.txt` to ensure correct graphic quality, as well as doing some other little tweaks to ensure everything works well. It also has an option to have the first setup/welcome screen, which is a nice addition.
