### ISSUE TITLE
 lockfile issue with Lubuntu

### ISSUE THREAD

**Issue by steeley** [wimpysworld/desktopify#75]
Using ubuntu server 64bit 20.04.lts when running the desktopify install command for lubuntu, it says there is a lockfile dpkg issue associated with unattended update mgr.

Removing these locks seems to fix it:
sudo rm /var/lib/apt/lists/lock
sudo rm /var/cache/apt/archives/lock
sudo rm /var/lib/dpkg/lock

**Comment by pascalandy** [comment]
thanks for the workaround!
