### ISSUE TITLE
Raspberry pie 4 ubuntu error

### ISSUE THREAD

**Issue by bco2135** [wimpysworld/desktopify#76]
I was setting up an ubuntu on a raspberry pie 4 and at the point I typed 

git clone https://github.com/wimpysworld/desktopify.git

this error pops up

fatal: unable to access 'http://github.com/wimpysworld/desktopify.git' Could not resolve host: github.com

can anyone help me?

**Comment by Itai-Nelken** [comment]
You are not connected to the internet.

**Comment by bco2135** [comment]
> You are not connected to the internet.

will ethernet work?

**Comment by bco2135** [comment]
okay Ill try to connect to the internet

**Comment by bco2135** [comment]
THANKS A LOT IT WORKED :D
